FROM rust:alpine3.21 AS build

ARG CARGO_LEPTOS_VERSION

RUN apk update && \
    apk add --no-cache musl-dev

WORKDIR /output
RUN cargo install --locked --root /output --version $CARGO_LEPTOS_VERSION cargo-leptos

FROM alpine:3.21

LABEL org.opencontainers.image.source=https://github.com/xJonathanLEI/docker-cargo-leptos

COPY --from=build /output/bin/cargo-leptos /usr/bin/

ENTRYPOINT [ "/usr/bin/cargo-leptos" ]
